Repository 9oormthon-univ/2024_DANPOONG_TEAM_27_FE, pull requests merged in 2024-11, with the labels that each got.

#9 [foundation] 앱 아이콘 추가
  assets/icons/add.svg
  assets/icons/arrow_down.svg
  assets/icons/arrow_left.svg
  assets/icons/arrow_right.svg
  assets/icons/book_filled.svg
  assets/icons/book_outlined.svg
  assets/icons/building_filled.svg
  assets/icons/building_outlined.svg
  assets/icons/calendar.svg
  assets/icons/chart_filled.svg
  assets/icons/chart_outlined.svg
  assets/icons/checklist.svg
  assets/icons/close_md.svg
  assets/icons/close_sm.svg
  assets/icons/delete.svg
  assets/icons/done.svg
  assets/icons/drop_down.svg
  assets/icons/dumbbell.svg
  assets/icons/edit.svg
  assets/icons/example1.svg
  assets/icons/fortune_colored.svg
  assets/icons/foutune_filled.svg
  assets/icons/goal.svg
  assets/icons/health_filled.svg
  assets/icons/health_outlined.svg
  assets/icons/heart_filled.svg
  assets/icons/heart_outlined.svg
  assets/icons/home_colored.svg
  assets/icons/home_outlined.svg
  assets/icons/note.svg
  assets/icons/pig_filled.svg
  assets/icons/pig_outlined.svg
  assets/icons/profile_colored.svg
  assets/icons/profile_fiiled.svg
  assets/icons/profile_outlined.svg
  assets/icons/puzzle.svg
  assets/icons/sleep.svg
  assets/icons/sort.svg
  assets/icons/vertical_dots.svg
  lib/ui/common/consts/assets.dart
Labels: foundation

#11 [foundation] 앱 colors 파일 설정
  lib/theme/boiler_colors.dart
  lib/theme/luckit_colors.dart
Labels: foundation

#19 [Bug] 타이포와 에셋 수정
  assets/icons/fortune_filled.svg
  assets/icons/profile_colored.svg
  assets/icons/profile_outlined.svg
  lib/theme/luckit_typos.dart
Labels: bug

#20 [Feature] 온보딩 목표 입력 화면
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/ui/common/widgets/custom_text_field.dart
  lib/ui/common/widgets/mission_text_field.dart
  lib/ui/home/home_view.dart
  lib/ui/onboarding/onboarding_state.dart
  lib/ui/onboarding/onboarding_view_model.dart
  lib/ui/onboarding/views/onboarding_birth_view.dart
  lib/ui/onboarding/views/onboarding_duration_view.dart
  lib/ui/onboarding/views/onboarding_goal_view.dart
  lib/ui/onboarding/widgets/check_icon_widget.dart
  lib/ui/onboarding/widgets/onboarding_bottom_button.dart
  lib/ui/onboarding/widgets/onboarding_layout.dart
  lib/ui/onboarding/widgets/onboarding_top_widget.dart
Labels: feature

#21 [Feature] 운세 탭 view와 위젯 제작
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/theme/luckit_colors.dart
  lib/ui/fortune/fortune_state.dart
  lib/ui/fortune/fortune_view.dart
  lib/ui/fortune/fortune_view_model.dart
  lib/ui/fortune/widgets/chip_list_widget.dart
  lib/ui/fortune/widgets/circular_graph_widget.dart
  lib/ui/fortune/widgets/fortune_app_bar_widget.dart
  lib/ui/fortune/widgets/fortune_card_widget.dart
  lib/ui/fortune/widgets/fortune_score_widget.dart
  lib/ui/fortune/widgets/icon_card_widget.dart
  lib/ui/fortune/widgets/time_fortune_graph_list_widget.dart
Labels: feature

#24 [Feature] 게임 기능 구현
  assets/animation/move/chicken_move.json
  assets/animation/move/cow_move.json
  assets/animation/move/dog_move.json
  assets/animation/move/dragon_move.json
  assets/animation/move/horse_move.json
  assets/animation/move/monkey_move.json
  assets/animation/move/mouse_move.json
  assets/animation/move/pig_move.json
  assets/animation/move/rabbit_move.json
  assets/animation/move/sheep_move.json
  assets/animation/move/snake_move.json
  assets/animation/move/tiger_move.json
  assets/animation/stop/chicken_stop.json
  assets/animation/stop/cow_stop.json
  assets/animation/stop/dog_stop.json
  assets/animation/stop/dragon_stop.json
  assets/animation/stop/horse_stop.json
  assets/animation/stop/monkey_stop.json
  assets/animation/stop/mouse_stop.json
  assets/animation/stop/pig_stop.json
  assets/animation/stop/rabbit_stop.json
  assets/animation/stop/sheep_stop.json
  assets/animation/stop/snake_stop.json
  assets/animation/stop/tiger_stop.json
  assets/images/game_background.png
  lib/ui/common/consts/assets.dart
  lib/ui/game/character_data.dart
  lib/ui/game/character_provider.dart
  lib/ui/game/lottie_player.dart
  lib/ui/game/walking_game.dart
  lib/ui/home/home_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#26 [foundation] 바텀 네브바와 라우트 설정
  lib/routes/app_router.dart
  lib/ui/common/consts/navigation_config.dart
  lib/ui/common/widget/bottom_navigation_bar_widget.dart
  lib/ui/common/widget/navigation_bar/custom_navigation_bar.dart
  lib/ui/common/widget/navigation_bar/navigation_provider.dart
  lib/ui/common/widget/navigation_bar/scaffold_with_navigation.dart
  lib/ui/fortune/fortune_view.dart
  lib/ui/home/home_view.dart
  lib/ui/profile/profile_view.dart
Labels: foundation

#28 [Feature] 농장 화면 구현
  android/app/src/main/AndroidManifest.xml
  assets/icons/home_filled.svg
  assets/icons/home_main_filled.svg
  assets/images/farm_background.png
  assets/images/farm_background_landscape.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/ui/common/consts/assets.dart
  lib/ui/farm/farm_character_provider.dart
  lib/ui/farm/farm_view.dart
  lib/ui/game/mission_character_provider.dart
  lib/ui/game/walking_game.dart
  lib/ui/home/home_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#31 [Feature] 온보딩 목표 기간/사주 입력 화면
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/ui/common/widgets/bottom_button_widget.dart
  lib/ui/common/widgets/custom_text_field.dart
  lib/ui/common/widgets/rounded_grey_text_widget.dart
  lib/ui/common/widgets/rounded_text_button_widget.dart
  lib/ui/onboarding/onboarding_state.dart
  lib/ui/onboarding/onboarding_view_model.dart
  lib/ui/onboarding/views/onboarding_birth_view.dart
  lib/ui/onboarding/views/onboarding_duration_view.dart
  lib/ui/onboarding/views/onboarding_goal_view.dart
  lib/ui/onboarding/widgets/check_icon_widget.dart
  lib/ui/onboarding/widgets/error_text_widget.dart
  lib/ui/onboarding/widgets/onboarding_bottom_button.dart
  lib/ui/onboarding/widgets/onboarding_date_input_field_widget.dart
  lib/ui/onboarding/widgets/onboarding_layout.dart
  lib/ui/onboarding/widgets/suggested_duration_widget.dart
Labels: feature

#37 [Feature] 목표 달성 화면
  assets/animation/appear/king_mouse_appear.json
  assets/animation/stop/king_mouse_stop.json
  assets/frame/chicken_frame.svg
  assets/frame/cow_frame.svg
  assets/frame/dog_frame.svg
  assets/frame/dragon_frame.svg
  assets/frame/horse_frame.svg
  assets/frame/monkey_frame.svg
  assets/frame/mouse_frame.svg
  assets/frame/pig_frame.svg
  assets/frame/rabbit_frame.svg
  assets/frame/sheep_frame.svg
  assets/frame/snake_frame.svg
  assets/frame/tiger_frame.svg
  assets/icons/cloud_1.svg
  assets/icons/cloud_2.svg
  assets/icons/cloud_3.svg
  assets/icons/cloud_4.svg
  assets/images/king_background.png
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/ui/common/consts/assets.dart
  lib/ui/common/widget/delete_dialog.dart
  lib/ui/common/widget/edit_dialog.dart
  lib/ui/farm/farm_character_provider.dart
  lib/ui/farm/farm_view.dart
  lib/ui/game/character_data.dart
  lib/ui/game/lottie_player.dart
  lib/ui/game/mission_character_provider.dart
  lib/ui/game/walking_game.dart
  lib/ui/goal_complete/goal_complete_state.dart
  lib/ui/goal_complete/goal_complete_view.dart
  lib/ui/goal_complete/goal_complete_view_model.dart
  lib/ui/goal_complete/widget/king_animation.dart
  lib/ui/goal_complete/widget/together_animal.dart
  lib/ui/home/home_view.dart
  lib/ui/login/login_view.dart
  pubspec.yaml
Labels: feature

#39 [feature] 홈의 투두 부분 작업
  assets/icons/done.svg
  assets/images/example1.png
  lib/main.dart
  lib/theme/luckit_colors.dart
  lib/ui/common/consts/assets.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/widgets/animated_card_widget.dart
  lib/ui/home/widgets/complete_goal_button_widget.dart
  lib/ui/home/widgets/fortune_score_text_widet.dart
  lib/ui/home/widgets/goal_status_bar_widget.dart
Labels: feature

#43 [Feature] 바텀시트와 모달
  lib/ui/common/consts/assets.dart
  lib/ui/common/widgets/custom_text_field.dart
  lib/ui/common/widgets/mission_text_field.dart
  lib/ui/farm/farm_view.dart
  lib/ui/game/lottie_player.dart
  lib/ui/game/mission_character_provider.dart
  lib/ui/game/walking_game.dart
  lib/ui/goal_complete/widget/king_animation.dart
  lib/ui/home/home_view.dart
  lib/ui/home/widget/add_mission_bottom_sheet.dart
  lib/ui/home/widget/bottom_sheet_textfield.dart
  lib/ui/home/widget/mission_complete_dialog.dart
  lib/ui/home/widget/mission_delete_bottom_sheet.dart
  lib/ui/home/widget/mission_manage_bottom_sheet.dart
  lib/ui/onboarding/views/onboarding_duration_view.dart
Labels: feature

#40 [Feat] 온보딩 디테일 추가
  assets/icons/warning.svg
  lib/ui/common/consts/assets.dart
  lib/ui/common/widgets/new_custom_text_field.dart
  lib/ui/onboarding/onboarding_state.dart
  lib/ui/onboarding/onboarding_view_model.dart
  lib/ui/onboarding/views/onboarding_birth_view.dart
  lib/ui/onboarding/views/onboarding_duration_view.dart
  lib/ui/onboarding/views/onboarding_goal_view.dart
  lib/ui/onboarding/widgets/birth_time_input_container_widget.dart
  lib/ui/onboarding/widgets/birth_time_text_field_widget.dart
  lib/ui/onboarding/widgets/check_icon_widget.dart
  lib/ui/onboarding/widgets/goal_suggestion_widget.dart
  lib/ui/onboarding/widgets/onboarding_app_bar.dart
  lib/ui/onboarding/widgets/onboarding_date_input_field_widget.dart
  lib/ui/onboarding/widgets/onboarding_date_input_row_widget.dart
  lib/ui/onboarding/widgets/onboarding_description_text_widget.dart
  lib/ui/onboarding/widgets/onboarding_duration_notice_widget.dart
  lib/ui/onboarding/widgets/onboarding_layout.dart
  lib/ui/onboarding/widgets/onboarding_number_text_field_widget.dart
  lib/ui/onboarding/widgets/onboarding_top_widget.dart
  lib/ui/onboarding/widgets/selected_goal_widget.dart
  lib/ui/onboarding/widgets/suggested_duration_widget.dart
Labels: feature

#58 [Feature] 카카오 로그인 구현
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/domain/auth/use_case/get_auth_use_case.dart
  lib/main.dart
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/service/network/dio_service.dart
  lib/ui/home/widget/mission_manage_bottom_sheet.dart
  lib/ui/login/login_state.dart
  lib/ui/login/login_view.dart
  lib/ui/login/login_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#46 [feature] 홈 화면 모달 연결 + 목표가 없을 때 화면 제작
  assets/icons/paw_colored.svg
  assets/images/1.5x/empty_dragon.png
  assets/images/2.0x/empty_dragon.png
  assets/images/3.0x/empty_dragon.png
  assets/images/4.0x/empty_dragon.png
  assets/images/empty_dragon.png
  lib/ui/common/consts/assets.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view.dart
  lib/ui/home/widget/add_mission_bottom_sheet.dart
  lib/ui/home/widget/mission_complete_dialog.dart
  lib/ui/home/widget/mission_manage_bottom_sheet.dart
  lib/ui/home/widgets/animated_card_widget.dart
  lib/ui/home/widgets/complete_goal_button_widget.dart
  lib/ui/home/widgets/go_to_farm_button_widget.dart
Labels: feature

#54 [Feature] 튜토리얼
  assets/icons/tutorial_cloud_1.svg
  assets/icons/tutorial_cloud_2.svg
  assets/icons/tutorial_cloud_3.svg
  assets/icons/tutorial_cloud_4.svg
  assets/images/1.5x/game_background_without_cloud.png
  assets/images/1.5x/tutorial_first_image.png
  assets/images/1.5x/tutorial_second_image.png
  assets/images/2.0x/game_background_without_cloud.png
  assets/images/2.0x/tutorial_first_image.png
  assets/images/2.0x/tutorial_second_image.png
  assets/images/3.0x/game_background_without_cloud.png
  assets/images/3.0x/tutorial_first_image.png
  assets/images/3.0x/tutorial_second_image.png
  assets/images/4.0x/game_background_without_cloud.png
  assets/images/4.0x/tutorial_first_image.png
  assets/images/4.0x/tutorial_second_image.png
  assets/images/game_background_without_cloud.png
  assets/images/tutorial_first_image.png
  assets/images/tutorial_second_image.png
  assets/images/white_background.png
  lib/routes/app_router.dart
  lib/routes/routes.dart
  lib/ui/common/consts/assets.dart
  lib/ui/game/horizontal_walking_game.dart
  lib/ui/onboarding/widgets/onboarding_bottom_button.dart
  lib/ui/profile/profile_view.dart
  lib/ui/tutorial/start_view.dart
  lib/ui/tutorial/tutorial_state.dart
  lib/ui/tutorial/tutorial_view.dart
  lib/ui/tutorial/tutorial_view_model.dart
  lib/ui/tutorial/widgets/cloud_animation.dart
  lib/ui/tutorial/widgets/tutorial_pages.dart
Labels: feature

#69 [Feature] 온보딩 추천 목표 api 연결
  lib/data/onboarding/entity/generated/suggestion_goal_entity.g.dart
  lib/data/onboarding/entity/suggestion_goal_entity.dart
  lib/data/onboarding/generated/onboarding_remote_data_source.g.dart
  lib/data/onboarding/onboarding_remote_data_source.dart
  lib/data/onboarding/onboarding_repository.dart
  lib/domain/onboarding/model/suggestion_goal_model.dart
  lib/domain/onboarding/use_case/get_suggestion_goal_list_use_case.dart
  lib/ui/onboarding/onboarding_state.dart
  lib/ui/onboarding/onboarding_view_model.dart
  lib/ui/onboarding/views/onboarding_goal_view.dart
  lib/ui/onboarding/widgets/goal_suggestion_widget.dart
Labels: feature

#74 [공통] 가로모드 방지
  assets/animation/no_shadow_move/no_shadow_chicken_move.json
  assets/animation/no_shadow_move/no_shadow_cow_move.json
  assets/animation/no_shadow_move/no_shadow_dog_move.json
  assets/animation/no_shadow_move/no_shadow_dragon_move.json
  assets/animation/no_shadow_move/no_shadow_horse_move.json
  assets/animation/no_shadow_move/no_shadow_monkey_move.json
  assets/animation/no_shadow_move/no_shadow_mouse_move.json
  assets/animation/no_shadow_move/no_shadow_pig_move.json
  assets/animation/no_shadow_move/no_shadow_rabbit_move.json
  assets/animation/no_shadow_move/no_shadow_sheep_move.json
  assets/animation/no_shadow_move/no_shadow_snake_move.json
  assets/animation/no_shadow_move/no_shadow_tiger_move.json
  assets/animation/no_shadow_stop/no_shadow_chicken_stop.json
  assets/animation/no_shadow_stop/no_shadow_cow_stop.json
  assets/animation/no_shadow_stop/no_shadow_dog_stop.json
  assets/animation/no_shadow_stop/no_shadow_dragon_stop.json
  assets/animation/no_shadow_stop/no_shadow_horse_stop.json
  assets/animation/no_shadow_stop/no_shadow_monkey_stop.json
  assets/animation/no_shadow_stop/no_shadow_mouse_stop.json
  assets/animation/no_shadow_stop/no_shadow_pig_stop.json
  assets/animation/no_shadow_stop/no_shadow_rabbit_stop.json
  assets/animation/no_shadow_stop/no_shadow_sheep_stop.json
  assets/animation/no_shadow_stop/no_shadow_snake_stop.json
  assets/animation/no_shadow_stop/no_shadow_tiger_stop.json
  lib/data/onboarding/generated/onboarding_remote_data_source.g.dart
  lib/data/onboarding/onboarding_remote_data_source.dart
  lib/main.dart
  lib/ui/common/consts/assets.dart
  lib/ui/farm/farm_character_provider.dart
  lib/ui/farm/farm_view.dart
  lib/ui/game/lottie_player.dart
  lib/ui/game/mission_character_provider.dart
  pubspec.yaml
Labels: feature
